### ISSUE TITLE
Bug: 出现异常

### ISSUE THREAD

**Issue by HolyFishhh** [RF-Tar-Railt/nonebot-plugin-arkgacha#13]
### 操作系统

Windows

### Python 版本

3.10.0

### NoneBot 版本

2.0.0

### 适配器

v11

### 描述问题

{}
06-03 15:10:11 [ERROR] nonebot | Failed to import "nonebot_plugin_arkgacha"
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/root/Shino/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/root/Shino/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "/root/Shino/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins
    return set(
  File "/root/Shino/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/Shino/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/root/Shino/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/Shino/.venv/lib/python3.10/site-packages/nonebot_plugin_arkgacha/__init__.py", line 8, in <module>
    from arknights_toolkit.gacha import ArknightsGacha, GachaUser
  File "/root/Shino/.venv/lib/python3.10/site-packages/arknights_toolkit/gacha/__init__.py", line 1, in <module>
    from .main import ArknightsGacha as ArknightsGacha
  File "/root/Shino/.venv/lib/python3.10/site-packages/arknights_toolkit/gacha/main.py", line 13, in <module>
    from ..update.gacha import generate
  File "/root/Shino/.venv/lib/python3.10/site-packages/arknights_toolkit/update/gacha/__init__.py", line 1, in <module>
    from .main import generate as generate
  File "/root/Shino/.venv/lib/python3.10/site-packages/arknights_toolkit/update/gacha/main.py", line 10, in <module>
    from .data import fetch
  File "/root/Shino/.venv/lib/python3.10/site-packages/arknights_toolkit/update/gacha/data.py", line 26, in <module>
    if "id" not in tables["陈"]:
KeyError: '陈'

### 复现步骤

安装后使用init报错，

### 期望的结果

输出后发现是tables为空了，是哪里没用设置吗？

**Comment by RF-Tar-Railt** [comment]
新版本要重新下载一遍数据

你可以用arkkit clear把旧的数据清理一下

**Comment by HolyFishhh** [comment]
> 新版本要重新下载一遍数据
> 
> 你可以用arkkit clear把旧的数据清理一下

第一次安装，看来是用nb脚手架的init会报错，切换到虚拟环境不用nb直接init的话就正常了。
感觉是没代码没做容错
if "id" not in tables["陈"]:
        logger.critical("operator resources has been outdated")
        logger.error("please execute `arkkit init --cover` in your command line")
        signal.raise_signal(signal.SIGINT)
这里是不是if判断里不应该直接取tables中的内容？如果tables为空会直接报错的

**Comment by HolyFishhh** [comment]
if "id" not in tables["陈"]:
        logger.critical("operator resources has been outdated")
        logger.error("please execute `arkkit init --cover` in your command line")
        signal.raise_signal(signal.SIGINT)
