### ISSUE TITLE
Bug: 解析PRTS返回内容出现IndexOutOfRange异常

### ISSUE THREAD

**Issue by fazer-y** [RF-Tar-Railt/nonebot-plugin-arkgacha#7]
### 操作系统

Linux

### Python 版本

3.10.0

### NoneBot 版本

2.00

### 适配器

OneBot V11

### 描述问题

05-18 11:13:28 [ERROR] nonebot | Failed to import "nonebot_plugin_arkgacha"
Traceback (most recent call last):
  File "/home/fazer/NB2/my-bot/Pallas-Bot/bot.py", line 26, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/root/anaconda3/envs/NB2/lib/python3.10/site-packages/nonebot/plugin/load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/root/anaconda3/envs/NB2/lib/python3.10/site-packages/nonebot/plugin/load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "/root/anaconda3/envs/NB2/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 175, in load_all_plugins
    return set(
  File "/root/anaconda3/envs/NB2/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/anaconda3/envs/NB2/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/root/anaconda3/envs/NB2/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/root/anaconda3/envs/NB2/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/anaconda3/envs/NB2/lib/python3.10/site-packages/nonebot_plugin_arkgacha/__init__.py", line 42, in <module>
    gacha = ArknightsGacha(config.arkgacha_pool_file or get_data_file("arkgacha", "pool.json"))
  File "/root/anaconda3/envs/NB2/lib/python3.10/site-packages/arknights_toolkit/gacha/main.py", line 43, in __init__
    asyncio.run(generate(self.file))
  File "/root/anaconda3/envs/NB2/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/anaconda3/envs/NB2/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/root/anaconda3/envs/NB2/lib/python3.10/site-packages/arknights_toolkit/update/gacha.py", line 215, in generate
    await fetch(table)
  File "/root/anaconda3/envs/NB2/lib/python3.10/site-packages/arknights_toolkit/update/gacha.py", line 122, in fetch
    data = root1.xpath("//script[@id='data_operator']")[0].text.splitlines()
IndexError: list index out of range

### 复现步骤

启动时出现问题

### 截图或日志

05-18 11:13:28 [ERROR] nonebot | Failed to import "nonebot_plugin_arkgacha"
Traceback (most recent call last):
  File "/home/fazer/NB2/my-bot/Pallas-Bot/bot.py", line 26, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/root/anaconda3/envs/NB2/lib/python3.10/site-packages/nonebot/plugin/load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/root/anaconda3/envs/NB2/lib/python3.10/site-packages/nonebot/plugin/load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "/root/anaconda3/envs/NB2/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 175, in load_all_plugins
    return set(
  File "/root/anaconda3/envs/NB2/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/anaconda3/envs/NB2/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/root/anaconda3/envs/NB2/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/root/anaconda3/envs/NB2/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/anaconda3/envs/NB2/lib/python3.10/site-packages/nonebot_plugin_arkgacha/__init__.py", line 42, in <module>
    gacha = ArknightsGacha(config.arkgacha_pool_file or get_data_file("arkgacha", "pool.json"))
  File "/root/anaconda3/envs/NB2/lib/python3.10/site-packages/arknights_toolkit/gacha/main.py", line 43, in __init__
    asyncio.run(generate(self.file))
  File "/root/anaconda3/envs/NB2/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/anaconda3/envs/NB2/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/root/anaconda3/envs/NB2/lib/python3.10/site-packages/arknights_toolkit/update/gacha.py", line 215, in generate
    await fetch(table)
  File "/root/anaconda3/envs/NB2/lib/python3.10/site-packages/arknights_toolkit/update/gacha.py", line 122, in fetch
    data = root1.xpath("//script[@id='data_operator']")[0].text.splitlines()
IndexError: list index out of range

**Comment by RF-Tar-Railt** [comment]
知道了，限定池的话prts不会直接跳转到寻访模拟界面😩

**Comment by RF-Tar-Railt** [comment]
升级 arknights_toolkit 版本到 0.5.8
